---
title: "STAT_E-109_Project"
author: "Erin Rebholz, Nadia Zafar, Imran Naskani, Max Yanover"
output: html_document
date: "2023-03-22"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Intitial package installation and data loading

```{r, packages}

#Install packages/libraries

library(dplyr)
library(ggplot2)
library(psych)
library(gridExtra)
library(MASS)
library(car)

```

```{r, load}

#Load in csv data for project

data <- read.csv('SDOH_Quality.csv')

#count_initial <- nrow(data)

#str(data)

```

```{r}


#Switch to numeric variables fo censuse/SDOH measures

data$median_age <- as.numeric(data$median_age)
data$per_white_non_hisp <- as.numeric(data$per_white_non_hisp)
data$med_inc_15plus_12mo <- as.numeric(data$med_inc_15plus_12mo)
data$per_below_poverty <- as.numeric(data$per_below_poverty)
data$per_college_grad_deg_25_plus <- as.numeric(data$per_college_grad_deg_25_plus)
          
#Switch to numeric variables for quality measures
data$COMP_HIP_KNEE <- as.numeric(data$COMP_HIP_KNEE)
data$MORT_30_AMI <- as.numeric(data$MORT_30_AMI)
data$MORT_30_CABG <- as.numeric(data$MORT_30_CABG)
data$MORT_30_COPD <- as.numeric(data$MORT_30_COPD)
data$MORT_30_HF <- as.numeric(data$MORT_30_HF)
data$MORT_30_PN <- as.numeric(data$MORT_30_PN)
data$MORT_30_STK <- as.numeric(data$MORT_30_STK)
data$PSI_03 <- as.numeric(data$PSI_03)
data$PSI_04 <- as.numeric(data$PSI_04)
data$PSI_06 <- as.numeric(data$PSI_06)
data$PSI_08 <- as.numeric(data$PSI_08)
data$PSI_09 <- as.numeric(data$PSI_09)
data$PSI_10 <- as.numeric(data$PSI_10)
data$PSI_12 <- as.numeric(data$PSI_12)
data$PSI_11 <- as.numeric(data$PSI_11)
data$PSI_13 <- as.numeric(data$PSI_13)
data$PSI_11 <- as.numeric(data$PSI_11)
data$PSI_14 <- as.numeric(data$PSI_14)
data$PSI_15 <- as.numeric(data$PSI_15)
data$PSI_90 <- as.numeric(data$PSI_90)

#Switch chr variables to factor
data$city <- as.factor(data$city)
data$state <- as.factor(data$state)
data$hospital_type <- as.factor(data$hospital_type)
data$hospital_ownership <- as.factor(data$hospital_ownership)
data$census_region <- as.factor(data$census_region)
data$census_division <- as.factor(data$census_division)

#check to make sure all are now integers
#str(data)
#View(data)
```
```{r,warning=FALSE}
for.ggplot <- data %>%  filter(!is.na(hosp_overall_rating) &  census_region != "#N/A")  %>% group_by(census_region, hosp_overall_rating) %>% summarize(count.hist = n())   

for.ggplot %>% ggplot(aes(x = hosp_overall_rating, y=count.hist,  fill = census_region)) +
  geom_col(position = "dodge")

```

```{r, warning=FALSE}
# best and worst hospital in the  sensu_region 

d.best.hp <-  data %>%  dplyr::select(4:5,8:17) %>%
          filter(!is.na(census_region)) %>%
          filter(census_region != "#N/A") %>%
          filter(!is.na(hosp_overall_rating)) %>%
          filter(hosp_overall_rating >= 3)
d.wort.hp <-  data %>%  dplyr::select(4:5,8:17) %>%
          filter(!is.na(census_region)) %>%
          filter(census_region != "#N/A") %>%
          filter(!is.na(hosp_overall_rating)) %>%
          filter(hosp_overall_rating < 3)


par(mfrow=c(2, 3))
d.best.hp  %>% filter(census_region == 'Midwest') %>%
  ggplot(aes(x=state,y=hosp_overall_rating), fill= census_region) +
  geom_boxplot(show.legend = T)  + 
  ggtitle('Hospital Overall Rating >= 3 by Census Region: MidWest') + 
  ylab('Hospital Overall Rating') + xlab("Census Region")

d.best.hp  %>% filter(census_region == 'South') %>%
  ggplot(aes(x=state,y=hosp_overall_rating), fill= census_region) +
  geom_boxplot(show.legend = T)  + 
  ggtitle('Hospital Overall Rating >= 3 by Census Region: South') + 
  ylab('Hospital Overall Rating') + xlab("Census Region")

d.best.hp  %>% filter(census_region == 'West') %>%
  ggplot(aes(x=state,y=hosp_overall_rating), fill= census_region) +
  geom_boxplot(show.legend = T)  + 
  ggtitle('Hospital Overall Rating >= 3 by Census Region: West') + 
  ylab('Hospital Overall Rating') + xlab("Census Region")


d.wort.hp  %>% filter(census_region == 'Midwest') %>%
  ggplot(aes(x=state,y=hosp_overall_rating), fill= census_region) +
  geom_boxplot(show.legend = T)  + 
  ggtitle('Hospital Overall Rating >= 3 by Census Region: MidWest') + 
  ylab('Hospital Overall Rating') + xlab("Census Region")

d.wort.hp  %>% filter(census_region == 'South') %>%
  ggplot(aes(x=state,y=hosp_overall_rating), fill= census_region) +
  geom_boxplot(show.legend = T)  + 
  ggtitle('Hospital Overall Rating >= 3 by Census Region: South') + 
  ylab('Hospital Overall Rating') + xlab("Census Region")

d.wort.hp  %>% filter(census_region == 'West') %>%
  ggplot(aes(x=state,y=hosp_overall_rating), fill= census_region) +
  geom_boxplot(show.legend = T)  + 
  ggtitle('Hospital Overall Rating >= 3 by Census Region: West') + 
  ylab('Hospital Overall Rating') + xlab("Census Region")

par(mfrow=c(2, 3))
d.best.hp  %>% filter(census_region == 'Midwest') %>%
  ggplot(aes(x=state,y=per_below_poverty), fill= census_region) +
  geom_boxplot(show.legend = T)  + 
  ggtitle('Hospital Overall Rating >= 3 by Census Region: MidWest') + 
  ylab('Below Poverty') + xlab("Census Region")

d.best.hp  %>% filter(census_region == 'South') %>%
  ggplot(aes(x=state,y=per_below_poverty), fill= census_region) +
  geom_boxplot(show.legend = T)  + 
  ggtitle('Hospital Overall Rating >= 3 by Census Region: South') + 
  ylab('Below Poverty') + xlab("Census Region")

d.best.hp  %>% filter(census_region == 'West') %>%
  ggplot(aes(x=state,y=per_below_poverty), fill= census_region) +
  geom_boxplot(show.legend = T)  + 
  ggtitle('Hospital Overall Rating >= 3 by Census Region: West') + 
  ylab('Below Poverty') + xlab("Census Region")


d.wort.hp  %>% filter(census_region == 'Midwest') %>%
  ggplot(aes(x=state,y=per_below_poverty), fill= census_region) +
  geom_boxplot(show.legend = T)  + 
  ggtitle('Hospital Overall Rating >= 3 by Census Region: MidWest') + 
  ylab('Below Poverty') + xlab("Census Region")

d.wort.hp  %>% filter(census_region == 'South') %>%
  ggplot(aes(x=state,y=per_below_poverty), fill= census_region) +
  geom_boxplot(show.legend = T)  + 
  ggtitle('Hospital Overall Rating >= 3 by Census Region: South') + 
  ylab('Below Poverty') + xlab("Census Region")

d.wort.hp  %>% filter(census_region == 'West' & !is.na(per_below_poverty)) %>%
  ggplot(aes(x=state,y=per_below_poverty), fill= census_region) +
  geom_boxplot(show.legend = T) +
  ggtitle('Hospital Overall Rating >= 3 by Census Region: West') + 
  ylab('Below Poverty') + xlab("Census Region")


```

```{r,warning=FALSE}

#histograms Mort_30_PN  by overall star rating

data  %>% filter(!is.na(hosp_overall_rating)) %>%
  ggplot(aes(x=MORT_30_PN, fill = hosp_overall_rating))+
  geom_histogram(show.legend = F, binwidth = 1) +
  facet_wrap(~hosp_overall_rating)

```
```{r, warning=FALSE}

#Overall Mean:
PH <- mean(data[,23],na.rm=TRUE)

#Generate Plot
data %>% ggplot(aes(data[,23], fill=as.factor(hosp_overall_rating)))+
  geom_histogram(position = "identity",show.legend = T, alpha = 0.4, bins = 50) +
  ggtitle(colnames(data)[23]) + 
  xlab(colnames(data)[23]) + ylab("Count")+
  geom_vline(xintercept=PH)
```
```{r}
# regression analysis  for  Mort_30_PN

pn_data <- data %>%  
   dplyr::select(4:5,8:17,23) %>% #Narrow to features to use in the model (plus one quality measure)
  filter(hosp_overall_rating != 'NA') %>% #remove NAs
  filter( !is.na(MORT_30_PN))  %>%  #Remove NAs from measure
  filter(census_region != '#N/A') %>%
  filter(!is.na(per_college_grad_deg_25_plus))  %>%
  filter (!is.na(per_below_poverty))  %>%
  filter(!is.na(med_inc_15plus_12mo))  %>%
  filter (!is.na(per_white_non_hisp)) 

# treat overall rating as a factor  
pn_data$hosp_overall_rating <- as.factor(pn_data$hosp_overall_rating)

set.seed(1234)

Mod <- lm (MORT_30_PN ~ census_region +per_college_grad_deg_25_plus + per_below_poverty + med_inc_15plus_12mo + per_white_non_hisp, pn_data)

summary(Mod)

#lm(formula = MORT_30_PN ~ per_white_non_hisp + census_region +  per_college_grad_deg_25_plus, data = pn_data)



```

```{r, warning=FALSE}
modaic <- stepAIC(Mod)


```
```{r, warning=TRUE}
# based on  Lowest step AIC model 

modf <- lm(MORT_30_PN ~ census_region + per_college_grad_deg_25_plus + per_below_poverty + 
    per_white_non_hisp, pn_data)
summary(modf)


```

```{r, warning=FALSE}
#After doing the summary of  suggestive setpAic model  per_below_poverty is not significant Remove it. 

modf.1 <- lm(MORT_30_PN ~ census_region + per_college_grad_deg_25_plus  + per_white_non_hisp, pn_data)
summary(modf.1)

```
```{r, warning=FALSE}
 vif(modf.1)

```

```{r,warning=FALSE}
# Analysis plots
par(mfrow=c(2,2))
plot(modf.1)

```
```{r, warning=False}
pairs.panels(pn_data)

```

```{r, warning=FALSE}
set.sel <- pn_data[,c(8:13)]

cor.plot(set.sel)
```