---
title: "STAT_E-109_Project"
author: "Erin Rebholz, Nadia Zafar, Imran Naskani, Max Yanover"
output: html_document
date: "2023-03-22"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Intitial package installation and data loading


```{r, packages}

#Install packages/libraries
#remove.packages('rlang')
#install.packages("rlang")
#remove.packages('vctrs')
#install.packages("vctrs")
#remove.packages('tibble')
#install.packages('tibble')
#install.packages('RToools')
#remove.packages('caret')
#install.packages('caret')
#Additional packages/libraries
#install.packages("Rtools")
#install.packages("psych")
#install.packages("PerformanceAnalytics")
#install.packages("olsrr")


library(MASS)
library(car)
library(dplyr)
library(ggplot2)
library(psych)
library(gridExtra)
library(PerformanceAnalytics)
library(olsrr)
library(nnet)
library(pROC) 
library(caret)
```


```{r, load}

#Load in csv data for project

data <- read.csv('SDOH_Quality.csv')

count_initial <- nrow(data)

str(data)

```
```{r}
#Filter to only acute care and critical access facilities

data <- data %>% filter(hospital_type == 'Acute Care Hospitals' |  hospital_type == 'Critical Access Hospitals') 

(count_cah_acutre <- nrow(data))

```
```{r}

# Drop facilities where zip code census demographic data is not available

data <- data %>% filter(median_age != "#N/A") 

(count_cah_acutre_zipNA <- nrow(data))

datana <- data %>% filter(!is.na(hosp_overall_rating ))
str(datana)
```



```{r}

#Switch to numeric variables fo censuse/SDOH measures

data$median_age <- as.numeric(data$median_age)
data$per_white_non_hisp <- as.numeric(data$per_white_non_hisp)
data$med_inc_15plus_12mo <- as.numeric(data$med_inc_15plus_12mo)
data$per_below_poverty <- as.numeric(data$per_below_poverty)
data$per_college_grad_deg_25_plus <- as.numeric(data$per_college_grad_deg_25_plus)
          
#Switch to numeric variables for quality measures
data$COMP_HIP_KNEE <- as.numeric(data$COMP_HIP_KNEE)
data$MORT_30_AMI <- as.numeric(data$MORT_30_AMI)
data$MORT_30_CABG <- as.numeric(data$MORT_30_CABG)
data$MORT_30_COPD <- as.numeric(data$MORT_30_COPD)
data$MORT_30_HF <- as.numeric(data$MORT_30_HF)
data$MORT_30_PN <- as.numeric(data$MORT_30_PN)
data$MORT_30_STK <- as.numeric(data$MORT_30_STK)
data$PSI_03 <- as.numeric(data$PSI_03)
data$PSI_04 <- as.numeric(data$PSI_04)
data$PSI_06 <- as.numeric(data$PSI_06)
data$PSI_08 <- as.numeric(data$PSI_08)
data$PSI_09 <- as.numeric(data$PSI_09)
data$PSI_10 <- as.numeric(data$PSI_10)
data$PSI_12 <- as.numeric(data$PSI_12)
data$PSI_11 <- as.numeric(data$PSI_11)
data$PSI_13 <- as.numeric(data$PSI_13)
data$PSI_11 <- as.numeric(data$PSI_11)
data$PSI_14 <- as.numeric(data$PSI_14)
data$PSI_15 <- as.numeric(data$PSI_15)
data$PSI_90 <- as.numeric(data$PSI_90)

#Switch chr variables to factor
data$city <- as.factor(data$city)
data$state <- as.factor(data$state)
data$hospital_type <- as.factor(data$hospital_type)
data$hospital_ownership <- as.factor(data$hospital_ownership)
data$census_region <- as.factor(data$census_region)
data$census_division <- as.factor(data$census_division)

#check to make sure all are now integers
str(data)

```

## Initial EDA - Overall Star Rating 

```{r}
#Histogram of Overall Hospital Star Rating

hist(data$hosp_overall_rating)


```

```{r}
#Figure 2
#Table of Overall Hospital Star Rating
(counts <- table(data$hosp_overall_rating))
```


```{r}
#Figure 2
#total number of rows in data
(nrows <- nrow(data))
```
```{r}
#------- Create a Data Table to Support Model Overview ----------
avg.PSI_90 <- 
data %>% filter(!is.na(PSI_90)) %>%  
summarize(Average= round(mean(PSI_90),3), Count = n(), Std_Dev = round(sd(PSI_90),3),.groups = 'drop') 
row.names(avg.PSI_90) <- c("PSI_90")

avg.PSI_90 <- as.data.frame(avg.PSI_90) 

avg.MORT_30_PN <- 
data %>% filter(!is.na(MORT_30_PN)) %>%  
summarize(Average= round(mean(MORT_30_PN),3), Count = n(), Std_Dev = round(sd(MORT_30_PN),3),.groups = 'drop') 
row.names(avg.MORT_30_PN) <- c("MORT_30_PN")

avg.MORT_30_PN <- as.data.frame(avg.MORT_30_PN) 

avg.MORT_30_HF <- 
data %>% filter(!is.na(MORT_30_HF)) %>%  
summarize(Average= round(mean(MORT_30_HF),3), Count = n(), Std_Dev = round(sd(MORT_30_HF),3),.groups = 'drop') 
row.names(avg.MORT_30_HF) <- c("MORT_30_HF")

avg.MORT_30_HF <- as.data.frame(avg.MORT_30_HF) 

avg.MORT_30_COPD <- 
data %>% filter(!is.na(MORT_30_COPD)) %>%  
summarize(Average= round(mean(MORT_30_COPD),3), Count = n(), Std_Dev = round(sd(MORT_30_COPD),3),.groups = 'drop') 
row.names(avg.MORT_30_COPD) <- c("MORT_30_COPD")

avg.MORT_30_COPD <- as.data.frame(avg.MORT_30_COPD) 

avg.rating <- 
data %>% filter(!is.na(hosp_overall_rating)) %>%  
summarize(Average= round(mean(hosp_overall_rating),3), Count = n(), Std_Dev = round(sd(hosp_overall_rating),3),.groups = 'drop') 
row.names(avg.rating) <- c("Hospital Overall Rating")

avg.rating <- as.data.frame(avg.rating) 


Blended <- rbind(avg.MORT_30_COPD,avg.MORT_30_HF,avg.MORT_30_PN,avg.PSI_90,avg.rating)

t(Blended)

```



```{r}

##SDOH Measures by Overall Hospital Rating

require(gridExtra)

plot1 <- data %>% ggplot(aes(x=factor(as.factor(hosp_overall_rating)),y =data[,13]))+
  geom_boxplot(show.legend = F) +
  coord_flip() +
  ggtitle(colnames(data)[13]) + 
  ylab('Measure Value') + xlab("Hosp_Overall_Rating")


plot2 <- data %>% ggplot(aes(x=factor(as.factor(hosp_overall_rating)),y =data[,14]))+
  geom_boxplot(show.legend = F) +
  coord_flip() +
  ggtitle(colnames(data)[14]) + 
  ylab('Measure Value') + xlab("Hosp_Overall_Rating")

plot3 <- data %>% ggplot(aes(x=factor(as.factor(hosp_overall_rating)),y =data[,15]))+
  geom_boxplot(show.legend = F) +
  coord_flip() +
  ggtitle(colnames(data)[15]) + 
  ylab('Measure Value') + xlab("Hosp_Overall_Rating")


plot4 <- data %>% ggplot(aes(x=factor(as.factor(hosp_overall_rating)),y =data[,16]))+
  geom_boxplot(show.legend = F) +
  coord_flip() +
  ggtitle(colnames(data)[16]) + 
  ylab('Measure Value') + xlab("Hosp_Overall_Rating")

plot5 <- data %>% ggplot(aes(x=factor(as.factor(hosp_overall_rating)),y =data[,17]))+
  geom_boxplot(show.legend = F) +
  coord_flip() +
  ggtitle(colnames(data)[17]) + 
  ylab('Measure Value') + xlab("Hosp_Overall_Rating")

#Aggregate into a single graph
grid.arrange(plot1, plot2, plot3, plot4, plot5, ncol=3)


#Save

g <- arrangeGrob(plot1, plot2, plot3, plot4, plot5, ncol=3) #generates g
ggsave("SDOH.png", g, width = 20, height = 15, units = "cm")



```


```{r}
##------- Boxplot: Star Rating vs Social Indicators -------------

#------- Boxplot: Star Rating vs Median Age -------------
social.ind1 <- data %>% filter(!is.na(hosp_overall_rating)) %>% 
ggplot(aes(x = hosp_overall_rating, y = median_age, fill = as.factor(hosp_overall_rating))) + 
geom_boxplot(show.legend = F)  + facet_wrap(~hospital_type) + 
ylab('Median Age') 

#------- Boxplot: Star Rating vs Percentage White Population -------------
social.ind2 <- data %>% filter(!is.na(hosp_overall_rating)) %>% 
ggplot(aes(x = hosp_overall_rating, y = per_white_non_hisp, fill = as.factor(hosp_overall_rating))) + 
geom_boxplot(show.legend = F) + facet_wrap(~hospital_type) + 
ylab('White Pop %') 

#------- Boxplot: Star Rating vs Population Below Poverty -------------
social.ind3 <- data %>% filter(!is.na(hosp_overall_rating)) %>% 
ggplot(aes(x = hosp_overall_rating, y = per_below_poverty, fill = as.factor(hosp_overall_rating))) + 
geom_boxplot(show.legend = F)  + facet_wrap(~hospital_type) + 
ylab('Below Poverty %') 

#------- Boxplot: Star Rating vs per_college_grad_deg_25_plus -------------
social.ind4 <- data %>% filter(!is.na(hosp_overall_rating)) %>% 
ggplot(aes(x = hosp_overall_rating, y = per_college_grad_deg_25_plus, fill = as.factor(hosp_overall_rating))) + 
geom_boxplot(show.legend = F)  + facet_wrap(~hospital_type) + 
ylab('College Grad Degree %') 

#------- Boxplot: Star Rating vs med_inc_15plus_12mo -------------
social.ind5 <- data %>% filter(!is.na(hosp_overall_rating)) %>% 
ggplot(aes(x = hosp_overall_rating, y = med_inc_15plus_12mo, fill = as.factor(hosp_overall_rating))) + 
geom_boxplot(show.legend = F) + facet_wrap(~hospital_type) + 
ylab('Median Income $') 

#Five Graphs in One
grid.arrange(social.ind1, social.ind2, social.ind3, social.ind4, social.ind5, ncol=2)
grid.social.ind3 <- arrangeGrob(social.ind1, social.ind2,social.ind3, social.ind4, social.ind5, ncol=2) 

```




```{r, warning = FALSE}

##Mortality and Complication Measures by Overall Hospital Rating -- FINAL GROUP

require(gridExtra)

#21,22,23,36

plot1 <- data %>% ggplot(aes(x=factor(as.factor(hosp_overall_rating)),y =data[,21]))+
  geom_boxplot(show.legend = F) +
  coord_flip() +
  ggtitle(colnames(data)[21]) + 
  ylab('Measure Value') + xlab("Hosp_Overall_Rating")


plot2 <- data %>% ggplot(aes(x=factor(as.factor(hosp_overall_rating)),y =data[,22]))+
  geom_boxplot(show.legend = F) +
  coord_flip() +
  ggtitle(colnames(data)[22]) + 
  ylab('Measure Value') + xlab("Hosp_Overall_Rating")

plot3 <- data %>% ggplot(aes(x=factor(as.factor(hosp_overall_rating)),y =data[,23]))+
  geom_boxplot(show.legend = F) +
  coord_flip() +
  ggtitle(colnames(data)[23]) + 
  ylab('Measure Value') + xlab("Hosp_Overall_Rating")


plot4 <- data %>% ggplot(aes(x=factor(as.factor(hosp_overall_rating)),y =data[,36]))+
  geom_boxplot(show.legend = F) +
  coord_flip() +
  ggtitle(colnames(data)[36]) + 
  ylab('Measure Value') + xlab("Hosp_Overall_Rating")

#Aggregate into a single graph
grid.arrange(plot1, plot2, plot3, plot4, ncol=2)


#Save
g <- arrangeGrob(plot1, plot2, plot3, plot4, ncol=2) #generates g
ggsave("Top4_Star.png", g, width = 25, height = 20, units = "cm")


```

```{r, warning = FALSE}

##Mortality and Complication Measures by Census Region -- FINAL GROUP

require(gridExtra)

#21,22,23,36

plot1 <- data  %>% ggplot(aes(x=census_division,y =data[,21]))+
  geom_boxplot(show.legend = F) +
  coord_flip() +
  ggtitle(colnames(data)[21]) + 
  ylab('Measure Value') + xlab("Census Division")


plot2 <- data %>% ggplot(aes(x=census_division,y =data[,22]))+
  geom_boxplot(show.legend = F) +
  coord_flip() +
  ggtitle(colnames(data)[22]) + 
  ylab('Measure Value') + xlab("Census Division")

plot3 <- data %>% ggplot(aes(x=census_division,y =data[,23]))+
  geom_boxplot(show.legend = F) +
  coord_flip() +
  ggtitle(colnames(data)[23]) + 
  ylab('Measure Value') + xlab("Census Division")


plot4 <- data %>% ggplot(aes(x=census_division,y =data[,36]))+
  geom_boxplot(show.legend = F) +
  coord_flip() +
  ggtitle(colnames(data)[36]) + 
  ylab('Measure Value') + xlab("Census Division")

#Aggregate into a single graph
grid.arrange(plot1, plot2, plot3, plot4, ncol=2)


#Save
g <- arrangeGrob(plot1, plot2, plot3, plot4, ncol=2) #generates g
ggsave("Census_Division_Meas.png", g, width = 25, height = 20, units = "cm")


```

```{r, warning = FALSE}

##Mortality and Complication Measures by Census Region -- FINAL GROUP

require(gridExtra)
require(forcats)

#21,22,23,36

plot1 <- data  %>% ggplot(aes(x=census_region,y =data[,21]))+
  geom_boxplot(show.legend = F) +
  coord_flip() +
  ggtitle(colnames(data)[21]) + 
  ylab('Measure Value') + xlab("Census Region")


plot2 <- data %>% ggplot(aes(x=census_region,y =data[,22]))+
  geom_boxplot(show.legend = F) +
  coord_flip() +
  ggtitle(colnames(data)[22]) + 
  ylab('Measure Value') + xlab("Census Region")

plot3 <- data %>% ggplot(aes(x=census_region,y =data[,23]))+
  geom_boxplot(show.legend = F) +
  coord_flip() +
  ggtitle(colnames(data)[23]) + 
  ylab('Measure Value') + xlab("Census Region")


plot4 <- data %>% ggplot(aes(x=census_region,y =data[,36]))+
  geom_boxplot(show.legend = F) +
  coord_flip() +
  ggtitle(colnames(data)[36]) + 
  ylab('Measure Value') + xlab("Census Region")

#Aggregate into a single graph
grid.arrange(plot1, plot2, plot3, plot4, ncol=2)


#Save
g <- arrangeGrob(plot1, plot2, plot3, plot4, ncol=2) #generates g
ggsave("Census_Region_Meas.png", g, width = 25, height = 20, units = "cm")


```




#Correlation Plot

```{r}

#Correlation Plots for Key Numeric Variables

cor_data <- data %>% dplyr::select(13:17,21,22,23,36)

cor.plot(cor_data)


```




## Linear regression - FOur Different Measures - 1 for each!

```{r}


```


```{r}
#Refresh on column names
colnames(data)

```

#Regression on the Composite measure for complications

```{r}

#Data cleaning -> Quality Measure 90 - > Composite Score for Other P Measures

mod_data <- data %>%  
   dplyr::select(4:5,8:17,36) %>% #Narrow to features to use in the model (plus one quality measure)
  filter(hosp_overall_rating != 'NA') %>% #remove NAs
  filter(PSI_90 != 'NA')  #Remove NAs from measure

# treat overall rating as a factor  
mod_data$hosp_overall_rating <- as.factor(mod_data$hosp_overall_rating)

table(mod_data$hospital_type)

```



```{r}
#Take a full model with all numeric terms

mod_mod <- lm(PSI_90~median_age+per_white_non_hisp+med_inc_15plus_12mo+
                per_below_poverty+per_college_grad_deg_25_plus+census_region,mod_data)

summary(mod_mod)

```


```{r}

#conduct a step AIC analysis to prioritize functions

new <- stepAIC(mod_mod)

```



```{r}

#Use model selected by stepAIC function
mod_modf <- lm(PSI_90~median_age+per_white_non_hisp+per_college_grad_deg_25_plus+census_region,mod_data)

summary(mod_modf)

```

```{r}
#VIF for PSI_90 
vif(mod_modf)

```


## Regression for Heart Failure

```{r}

#Data cleaning -> MORT_30_HF - > 30 Day Heart Failure Death Rate

hf_data <- data %>%  
  dplyr::select(4:5,8:17,22) %>% #Narrow to features to use in the model (plus one quality measure)
  filter(hosp_overall_rating != 'NA') %>% #remove NAs
  filter(MORT_30_HF != 'NA')  #Remove NAs from measure

# treat overall rating as a factor  
hf_data$hosp_overall_rating <- as.factor(hf_data$hosp_overall_rating)


#Data cleaning -> MORT_30_HF - > 30 Day Heart Failure Death Rate
detach(package:MASS, unload = TRUE)
hf_data <- data %>% select(11,13:17,22) 
library(MASS)
hf_data <- hf_data[complete.cases(hf_data),] #Only complete cases

  
multi.model.hf <- lm(MORT_30_HF ~ census_region + per_white_non_hisp +
                      med_inc_15plus_12mo + per_college_grad_deg_25_plus, data = hf_data)

summary(multi.model.hf)

vif(multi.model.hf)



```


## Regression for Pneumonia

```{r}

#Data cleaning -> MORT_30_PN - > 30 Day pneumonia death rate

pn_data <- data %>%  
  dplyr::select(4:5,8:17,23) %>% #Narrow to features to use in the model (plus one quality measure)
  filter(hosp_overall_rating != 'NA') %>% #remove NAs
  filter(MORT_30_PN != 'NA')  #Remove NAs from measure

# treat overall rating as a factor  
pn_data$hosp_overall_rating <- as.factor(pn_data$hosp_overall_rating)

```

## Regression for COPD

```{r}

#Data cleaning -> MORT_30_COPD - > 30 Day COPD death rate

copd_data <- data %>%  
  dplyr::select(4:5,8:17,21) %>% #Narrow to features to use in the model (plus one quality measure)
  filter(hosp_overall_rating != 'NA') %>% #remove NAs
  filter(MORT_30_COPD != 'NA')  #Remove NAs from measure

# treat overall rating as a factor  
copd_data$hosp_overall_rating <- as.factor(copd_data$hosp_overall_rating)

#Data cleaning -> MORT_30_COPD - > 30 Day Heart Failure Death Rate
detach(package:MASS, unload = TRUE)
copd_data <- data %>% select(11,13:17,21) 
library(MASS)
copd_data <- copd_data[complete.cases(copd_data),] #Only complete cases

multi.model.copd <- lm(MORT_30_COPD ~ census_region + per_white_non_hisp + 
    med_inc_15plus_12mo, data = copd_data)
summary(multi.model.copd)
vif(multi.model.copd)



```
```{r}
nrow(mod_data)
nrow(copd_data)
nrow(pn_data)
nrow(hf_data)

```

## Logistic Regression

```{r}
##---------Actual Code begins to create logistic model -------------

hf_data <- data %>%  
  dplyr::select(10:11,13:36) %>% #Narrow to features to use in the model (plus one quality measure)
  filter(hosp_overall_rating != 'NA') %>% #remove NAs
  filter(MORT_30_HF != 'NA')   %>%  #Remove NAs from measure
  filter(census_region != '#N/A')   

hf_data <- hf_data[complete.cases(hf_data),] #Only complete cases


hf_data_log <- hf_data

#hf_data_log$hosp_overall_rating <- as.numeric(hf_data_log$hosp_overall_rating)
hf_data_log[hf_data_log$hosp_overall_rating < 4,]$hosp_overall_rating <- 0
hf_data_log[hf_data_log$hosp_overall_rating >= 4,]$hosp_overall_rating <- 1
hf_data_log$hosp_overall_rating <- as.factor(hf_data_log$hosp_overall_rating)

#table(hf_data_log$hosp_overall_rating)

  # Separate into test/train  
  set.seed(1234)
  #data partitioning test/train
  ind <- sample(2, nrow(hf_data_log), replace = T, prob=c(0.6,0.4))
  hf_train_log <- hf_data_log[ind == 1,]
  hf_test_log <- hf_data_log[ind ==2, ]

#  model_train_log <- glm(hosp_overall_rating ~ census_region + median_age + 
#    per_white_non_hisp + per_below_poverty + COMP_HIP_KNEE + 
#    MORT_30_AMI + MORT_30_CABG + MORT_30_COPD + MORT_30_PN + 
#    MORT_30_STK + PSI_03 + PSI_04 + PSI_06 + PSI_08 + PSI_13, data = hf_train_log, family #= 'binomial' )

  model_train_log <- glm(hosp_overall_rating ~ census_region + median_age + 
    per_white_non_hisp + per_below_poverty + COMP_HIP_KNEE + 
    MORT_30_CABG + MORT_30_PN + 
    MORT_30_STK + PSI_03 + PSI_04, data = hf_train_log, family = 'binomial' )
  
    summary(model_train_log)
  (full_model <- model_train_log %>% stepAIC(trace = FALSE))
```


```{r}
#CM - train data
p_log_train <- predict(model_train_log, hf_train_log, type = 'response')
pred_log_train <- ifelse(p_log_train > 0.5, 1, 0)
confusionMatrix(factor(pred_log_train), factor(hf_train_log$hosp_overall_rating), positive = '1')
```

```{r}
#CM - test data
p_log_test <- predict(model_train_log, hf_test_log, type = 'response')
pred_log_test <- ifelse(p_log_test > 0.5, 1, 0)
confusionMatrix(factor(pred_log_test), factor(hf_test_log$hosp_overall_rating), positive = '1')
```

```{r}
#ROC Curve
p_log_train <- predict(model_train_log, hf_train_log, type = 'response')
r_train <- multiclass.roc(hf_train_log$hosp_overall_rating, p_log_train, percent = TRUE)
roc_train <- r_train[['rocs']]
r1_train <- roc_train[[1]]
```

```{r}
p_log_test <- predict(model_train_log, hf_test_log, type = 'response')
r_test <- multiclass.roc(hf_test_log$hosp_overall_rating, p_log_test, percent = TRUE)
roc_test <- r_test[['rocs']]
r1_test <- roc_test[[1]]
```

```{r}
plot.roc(r1_train,col= "red", lwd = 3,
         print.auc = T,
         auc.polygon= T,
         max.auc.polygon = T,
         print.thres = T,
         main = "ROC Curve for Hospital Rating")
plot(r1_test, add = T, col = "blue",
     lwd = 3, print.thres = T)
```

```{r}
(coords(r1_train, "best", ret="threshold", transpose = FALSE))
(coords(r1_test, "best", ret="threshold", transpose = FALSE))
```



